version: '3.7'
services:

  discovery-service:
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
      - 8866:8866

  repository-service:
    build:
      context: repository-service
      dockerfile: Dockerfile
    ports:
      - 8001:8080
    depends_on:
      - discovery-service
