version: '3.7'
services:

  config-service:
    build:
      context: config-service
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 5s
      timeout: 10s
      retries: 3
    env_file:
    - github.env
    ports:
    - "8888:8888"

  discovery-service:
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
    - "8761:8761"

    depends_on:
      - config-service

  repository-service:
    build:
      context: repository-service
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      - config-service
      - discovery-service
