version: '3.7'
services:

  config-service:
    build:
      context: config-service
      dockerfile: Dockerfile
    env_file:
    - github.env
    ports:
    - "8888:8888"

  discovery-service:
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
    - "8761:8761"
    restart: on-failure
    depends_on:
      - config-service

  repository-service:
    build:
      context: repository-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - config-service
      - discovery-service

  basic-client-service:
    build:
      context: basic-client-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - config-service
      - discovery-service

  gateway-service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - config-service
    - discovery-service
    - repository-service
    - basic-client-service
